// Detailed educational content per indicator. Static reference material —
// edit freely; not regenerated by the daily workflow.
const INDICATOR_CONTENT = {
    case_shiller: {
        whatItMeasures: 'The S&P/Case-Shiller National Home Price Index tracks repeat-sale prices of single-family homes across the United States. Unlike median sale price, it controls for the mix of homes sold each month, so it isolates true price change rather than shifts in what types of homes are trading.',
        whyItMatters: 'When this index rises far faster than wages or rents, it signals a bubble. The 2006 peak ran roughly 96% above 2000 levels — a pace impossible to sustain on income growth alone. The disconnect between prices and fundamentals is the canonical bubble warning sign.',
        historicalContext: [
            {date: 'July 2006', label: 'Bubble peak (~185)', note: 'Prices had nearly doubled in 6 years on subprime credit expansion.'},
            {date: 'February 2012', label: 'Crash trough (~134)', note: '−27% nationally; >50% in Las Vegas, Phoenix, Miami.'},
            {date: 'June 2022', label: 'Post-COVID peak (~305)', note: 'Driven by ultra-low rates and remote-work migration.'},
        ],
        interpretation: 'Read this alongside affordability metrics. High prices alone are not bearish if incomes and rents have kept pace. The signal is when this index breaks far above its 20-year trendline AND household debt-to-income spikes.',
    },
    median_price: {
        whatItMeasures: 'The median price at which existing homes actually sold each quarter. Reflects the literal price someone paid for a typical home, not adjusted for the mix of property types or geographic shifts in sales activity.',
        whyItMatters: 'Median price is what most people emotionally track ("what is the typical home worth?"). It moves with Case-Shiller but lags slightly because it can be skewed by which segments are transacting. When luxury sales freeze, median can drop even if same-home prices rise.',
        historicalContext: [
            {date: '2007 Q1', label: 'Pre-crash high', note: 'Median sale ~$257K nationally.'},
            {date: '2009 Q1', label: 'Crash low', note: 'Median ~$208K — back to 2003 levels.'},
            {date: '2022 Q4', label: 'Post-COVID peak', note: 'Median pushed past $479K on rate-shock distortion.'},
        ],
        interpretation: 'Compare to median household income for the affordability picture. Healthy ratio: ~3.5×. Bubble territory: 5×+. Use Case-Shiller as the better signal — median is more volatile and easier to misinterpret.',
    },
    homeownership: {
        whatItMeasures: 'The share of US households that own (rather than rent) their primary residence. Tracked quarterly by the Census Bureau.',
        whyItMatters: 'Homeownership tends to rise during easy-credit booms and fall during deleveraging. The 2004 peak (69.2%) was achieved by extending credit to buyers who could not sustain payments — many of them were forced back into renting after 2008. A falling rate signals tightening credit, foreclosures, or prices outpacing what new buyers can afford.',
        historicalContext: [
            {date: '2004 Q4', label: 'All-time peak (69.2%)', note: 'Subprime + zero-down loans pulled in marginal buyers.'},
            {date: '2016 Q2', label: 'Post-crash trough (62.9%)', note: 'Foreclosures + tight credit reversed 30 years of gains.'},
            {date: '2024+', label: 'Slow recovery (~65-66%)', note: 'Affordability crisis blocking first-time buyers.'},
        ],
        interpretation: 'Falling homeownership during a price boom is an early warning — it suggests prices are rising not because buyers can afford them, but because investors are pricing renters out. That happened in 2005 and is happening in some metros now.',
    },
    mortgage_delinquency: {
        whatItMeasures: 'The percentage of single-family residential mortgages held by US commercial banks that are 30+ days past due. Released quarterly by the Federal Reserve.',
        whyItMatters: 'This is the most direct measure of whether borrowers are still making their payments. Unlike valuation indicators (which can stay elevated for years before a crash), delinquency moves only when real economic stress hits households. It is a lagging signal — by the time it spikes, the crash has already started — but its trajectory tells you how deep the damage is.',
        historicalContext: [
            {date: '2006', label: 'Pre-crash baseline (~2%)', note: 'Historically normal range for healthy economy.'},
            {date: '2010 Q1', label: 'Crisis peak (~11.3%)', note: 'One in nine mortgages delinquent — unprecedented in modern data.'},
            {date: '2019', label: 'Post-recovery (~2.5%)', note: 'Tighter post-Dodd-Frank lending kept this contained.'},
        ],
        interpretation: 'Below 3% = healthy. 3-5% = stress emerging. 5%+ = systemic problem. Watch the rate of change more than the level — a doubling in 12 months is the alarm bell, regardless of starting point.',
    },
    debt_service_ratio: {
        whatItMeasures: 'Household debt payments (mortgages, auto loans, credit cards, student loans) as a percentage of after-tax disposable income. Published quarterly by the Federal Reserve.',
        whyItMatters: 'This captures household financial fragility better than total debt levels. A family carrying $500K in mortgage debt is fine if their income easily covers payments; the same debt is catastrophic if rates rise or income falls. The 2007 peak coincided with mortgage debt crossing 100% of disposable income — a tipping point.',
        historicalContext: [
            {date: '1980-2000', label: 'Stable range (~10.5-12%)', note: 'Normal mortgage-driven household leverage.'},
            {date: '2007 Q4', label: 'All-time peak (~13.2%)', note: 'Households spending nearly 1/8 of after-tax income servicing debt.'},
            {date: '2021 Q1', label: 'Pandemic low (~8.4%)', note: 'Stimulus + forbearance + low rates = lowest in series history.'},
        ],
        interpretation: 'Above 12.5% historically signals dangerous fragility — a small income shock can cascade into mass defaults. The 2007 peak was reached gradually over a decade; rapid rises are the more concerning pattern.',
    },
    real_income: {
        whatItMeasures: 'Annual median US household income, adjusted for inflation. The middle household — half of America earns more, half less.',
        whyItMatters: 'This is the denominator in every affordability calculation. When real wages stagnate while home prices climb, the gap is filled by debt — until the debt becomes unsustainable. The 2000-2012 period saw real incomes essentially flat while home prices doubled. That math could not work, and it didn\'t.',
        historicalContext: [
            {date: '2000', label: 'Pre-bubble peak', note: 'Real median income ~$70.5K (in 2022 dollars).'},
            {date: '2012', label: 'Post-crash trough', note: 'Real income ~$66K — Americans poorer in real terms than 12 years prior.'},
            {date: '2019', label: 'Recovery high', note: 'Real income ~$78K, finally surpassing the 2000 peak.'},
        ],
        interpretation: 'Lower or stagnant real income with rising home prices = unsustainable. Rising real income with rising home prices = healthy. Watch the trend, not the absolute number.',
    },
    housing_starts: {
        whatItMeasures: 'The number of new privately-owned housing units that broke ground (foundation poured) each month, reported as a seasonally-adjusted annual rate.',
        whyItMatters: 'Starts are the leading indicator of housing supply 6-12 months out. They are also the most cyclical sector of the economy — builders pause projects fast when sales slow. The 79% peak-to-trough collapse from 2006 to 2009 was the deepest since the series began in 1959, and it dragged the entire economy down with it.',
        historicalContext: [
            {date: 'January 2006', label: 'Bubble peak (2.27M)', note: 'Highest annualized rate since 1973.'},
            {date: 'April 2009', label: 'Crash trough (478K)', note: '−79% — most builders went bankrupt or paused indefinitely.'},
            {date: '2022-2024', label: 'Post-COVID range (~1.4M)', note: 'Mortgage rate shock froze new construction without crashing it.'},
        ],
        interpretation: 'Starts collapsing while inventory rises = builders pulling back ahead of trouble. Starts strong while prices high = healthy expansion. Use this with months-of-inventory for a fuller supply picture.',
    },
    months_inventory: {
        whatItMeasures: 'How many months it would take to sell all currently-listed new homes at the current sales pace. A direct measure of supply/demand balance in the new-home market.',
        whyItMatters: 'This is the cleanest "is the market overheating or stalling" signal in housing. <4 months = sellers\' market (rapid price gains). 4-6 = balanced. >6 = buyers\' market (price pressure). >10 = oversupply that historically takes years to clear. The 2008 crash had 12+ months of inventory at the peak.',
        historicalContext: [
            {date: '2009 Q1', label: 'Crash peak (~12 months)', note: 'Builders stuck with massive unsold inventory.'},
            {date: '2021 Q3', label: 'Pandemic low (~3.4 months)', note: 'Bidding wars, prices up 18% YoY.'},
            {date: '2024+', label: 'Rising (~9 months)', note: 'New-home inventory growing as affordability bites.'},
        ],
        interpretation: 'Crossing 7 months from below = warning. Crossing 10 months = serious oversupply forming. Inventory builds slowly, then crashes prices fast once it triggers builder discounting.',
    },
    new_home_sales: {
        whatItMeasures: 'New single-family homes sold per month (annualized seasonally-adjusted rate). Represents brand-new construction, not resale of existing homes.',
        whyItMatters: 'New home sales are 10-15% of total housing volume but the most economically important slice — every new home triggers job creation in construction, materials, and household goods. When new sales fall, the economic ripple is much bigger than the unit count suggests.',
        historicalContext: [
            {date: '2005', label: 'Bubble peak (~1.39M)', note: 'Builders chasing speculative buyer demand.'},
            {date: '2011', label: 'Crash trough (~306K)', note: '−78% from peak; lowest since records began in 1963.'},
            {date: '2020', label: 'Stimulus surge (~1.04M)', note: 'Briefly back to bubble-era pace.'},
        ],
        interpretation: 'Sustained sales below 600K = recession-level weakness. Above 1.2M = hot market territory. The trajectory matters more than the level — a 30% YoY decline is the alarm regardless of starting point.',
    },
    unemployment: {
        whatItMeasures: 'The percentage of the labor force that is actively looking for work but doesn\'t have a job. Released monthly by the Bureau of Labor Statistics.',
        whyItMatters: 'Job loss is the #1 driver of mortgage default. People keep paying their mortgage as long as they have a paycheck — even when they\'re underwater. When they lose income, they default within months. Unemployment leads delinquency by 3-6 months in nearly every housing crash on record.',
        historicalContext: [
            {date: 'May 2007', label: 'Pre-crash low (4.4%)', note: 'Tight labor market masked emerging credit stress.'},
            {date: 'October 2009', label: 'Crisis peak (10.0%)', note: '15M+ Americans out of work; mortgage defaults followed.'},
            {date: 'April 2020', label: 'COVID spike (14.8%)', note: 'Brief but extreme; absorbed by stimulus + forbearance.'},
        ],
        interpretation: 'Rising from below 4% toward 5% = expansion ending. Above 6% = recession likely; expect mortgage delinquencies to follow within 6 months. The Sahm Rule: when 3-month average rises 0.5% from 12-month low, recession has likely begun.',
    },
    mortgage_rate: {
        whatItMeasures: 'The average interest rate offered on a new 30-year fixed-rate mortgage in the United States. Released weekly by Freddie Mac.',
        whyItMatters: 'Mortgage rates are the single biggest lever on housing affordability. A buyer with a $3K/month budget can afford ~$565K at 4% rates but only ~$420K at 7% rates — a 25% difference in purchasing power. When rates spike, sales freeze, then prices follow with a 6-12 month lag.',
        historicalContext: [
            {date: 'October 1981', label: 'All-time peak (18.6%)', note: 'Volcker shock — Fed killed inflation by killing housing.'},
            {date: 'January 2021', label: 'Pandemic low (2.65%)', note: 'Generational refinance opportunity; locked in millions of borrowers.'},
            {date: 'October 2023', label: 'Recent peak (7.79%)', note: 'Highest in 23 years; froze the resale market.'},
        ],
        interpretation: 'Rapid rises (>1.5% in 12 months) historically precede housing slowdowns within 6-12 months. The pace of change matters more than the absolute level — buyers adjust to high rates if they\'re stable, but rapid rises produce affordability shocks.',
    },
    yield_curve: {
        whatItMeasures: 'The difference between the 10-year and 2-year US Treasury yields. When 10-year yields exceed 2-year, the curve is "normal" (positive). When 2-year exceeds 10-year, the curve is "inverted" (negative).',
        whyItMatters: 'Yield curve inversions have preceded every US recession since 1955 — 8 of 8. The mechanism: when investors expect future rate cuts (because they expect a recession), long-term yields fall below short-term. Every modern housing crash has been preceded by an inversion 6-18 months prior.',
        historicalContext: [
            {date: 'June 2006', label: 'Inversion before GFC', note: 'Curve went negative ~18 months before the 2008 crash.'},
            {date: 'August 2019', label: 'Inversion before COVID recession', note: 'Curve inverted briefly; recession arrived 7 months later (helped by COVID).'},
            {date: 'July 2022 - Sept 2024', label: 'Longest inversion in history', note: 'Lasted 26 months but didn\'t produce the expected recession — debate rages.'},
        ],
        interpretation: 'Inversions have a perfect track record but extremely variable lag (6-24 months). A reverting curve (going from negative back to positive after deep inversion) has historically been the more reliable "recession is imminent" trigger.',
    },
    fed_funds: {
        whatItMeasures: 'The interest rate at which US banks lend reserve balances to each other overnight. Set within a target range by the Federal Open Market Committee (FOMC) — the Fed\'s primary monetary policy tool.',
        whyItMatters: 'When the Fed raises rates aggressively, asset prices — including housing — typically fall within 12-24 months. Every modern housing peak has been preceded by a rate-tightening cycle: 1989 (S&L crisis), 2006 (subprime crisis), 2022 (rate shock). The mechanism is simple — higher Fed Funds → higher mortgage rates → reduced affordability → falling sales → falling prices.',
        historicalContext: [
            {date: 'June 2006', label: 'Pre-crash peak (5.25%)', note: 'Held until housing was visibly cracking; cuts started in Aug 2007.'},
            {date: 'December 2008', label: 'Zero lower bound (0-0.25%)', note: 'Held there for 7 years; created the next bubble.'},
            {date: 'July 2023', label: 'Recent peak (5.25-5.50%)', note: 'Highest since 2001; mortgage rates followed to 7%+.'},
        ],
        interpretation: 'Rate-cutting cycles often coincide with crashes — by the time the Fed cuts, the damage is already done. Watch the pace of HIKES (>3% in 18 months = high stress on housing) and the SHAPE of the cycle (long pause at peak = late-cycle, near risk).',
    },
    consumer_sentiment: {
        whatItMeasures: 'The University of Michigan\'s monthly survey of US consumer attitudes about the economy, personal finances, and big-ticket purchases. Indexed to 1966 = 100.',
        whyItMatters: 'Sentiment is reflexive — when people feel poor, they spend less, postpone home purchases, and stop bidding on listings. That alone can tip a wobbly market into a crash. Sentiment troughs have historically coincided with housing market bottoms (June 2008, June 2022) — useful for spotting capitulation.',
        historicalContext: [
            {date: 'August 2007', label: 'Pre-crash trough', note: 'Sentiment cratered to 84.9 — a leading signal of recession.'},
            {date: 'June 2022', label: 'All-time low (50.0)', note: 'Lower than 2008 — driven by inflation shock; market did not crash.'},
            {date: '2025+', label: 'Choppy ~70 range', note: 'Affordability concerns weighing on sentiment despite low unemployment.'},
        ],
        interpretation: 'Low sentiment + low unemployment = anomaly worth investigating. Low sentiment + rising unemployment = recession unfolding. Use as a confirming signal alongside hard data; it can be too pessimistic for too long without a crash actually arriving.',
    },
};
