import { PLACEHOLDER } from './runner.js';
import { EXAM_CHALLENGES } from './exam-challenges.js';

// Every challenge is edited as a whole playbook file. The play header is pre-written.
const HEADER = '---\n- name: Display facts\n  hosts: servera\n  tasks:\n';
const indent = (text) => text.split('\n').map((line) => (line ? `    ${line}` : line)).join('\n');
const playbook = (taskText) => HEADER + indent(taskText);
const taskText = (name, msg) => `- name: ${name}\n  ansible.builtin.debug:\n    msg: "${msg}"\n`;
const task = (name, msg) => playbook(taskText(name, msg));
// Tier 1: the task is written already, with one blank to fill in.
const blank = (expression) => task('Display the fact', `{{ ${expression} }}`);
const FILL_IN = blank(PLACEHOLDER);
// Tiers 2 and up: the header, then an indented empty line where the task goes.
const EMPTY_PLAY = `${HEADER}    `;

const FUNDAMENTALS = [
  {
    id: 't1-hostname',
    title: 'Short hostname',
    tier: 1,
    prompt: 'Which fact holds the short hostname, without the domain? Replace FACT_GOES_HERE with the expression that reads it, then run the playbook.',
    hint: "In the terminal, run: ansible servera -m setup | grep -i hostname. The output shows ansible_hostname; inside ansible_facts you drop the ansible_ prefix.",
    requires: [['hostname']],
    starter: FILL_IN,
    solution: blank("ansible_facts['hostname']"),
  },
  {
    id: 't1-os-family',
    title: 'Red Hat family',
    tier: 1,
    prompt: 'Which fact proves this host belongs to the Red Hat family, so a task could safely use dnf? Replace FACT_GOES_HERE with the expression.',
    hint: "Run: ansible servera -m setup | grep -E 'distribution|os_family'. Only one of them says RedHat on a CentOS Stream host.",
    requires: [['os_family']],
    starter: FILL_IN,
    solution: blank("ansible_facts['os_family']"),
  },
  {
    id: 't1-pkg-mgr',
    title: 'Package manager',
    tier: 1,
    prompt: 'Which fact names the package manager this host uses? Replace FACT_GOES_HERE with the expression.',
    hint: "Run: ansible servera -m setup | grep -i pkg.",
    requires: [['pkg_mgr']],
    starter: FILL_IN,
    solution: blank("ansible_facts['pkg_mgr']"),
  },
  {
    id: 't1-ipv4',
    title: 'Default IPv4 address',
    tier: 1,
    prompt: 'Replace FACT_GOES_HERE with the expression for the IPv4 address on the default-route interface. This one is nested.',
    hint: "Run: ansible servera -m setup | grep -A12 default_ipv4 to see the nested keys. Chain one lookup per level: ansible_facts['outer']['inner'].",
    requires: [['default_ipv4', 'address']],
    starter: FILL_IN,
    solution: blank("ansible_facts['default_ipv4']['address']"),
  },
  {
    id: 't1-first-mount-device',
    title: 'First mount device',
    tier: 1,
    prompt: "Replace FACT_GOES_HERE with the expression for the device behind the first entry in the 'mounts' list.",
    hint: "Run: ansible servera -m setup -a 'filter=ansible_mounts'. It is a list, so pick an item by position first: ['mounts'][0], then the key you want.",
    requires: [['mounts', 0, 'device']],
    starter: FILL_IN,
    solution: blank("ansible_facts['mounts'][0]['device']"),
  },
  {
    id: 't2-hostname',
    title: 'Print the hostname',
    tier: 2,
    prompt: "Add a task beneath tasks: that prints the target host's short hostname when the playbook runs.",
    hint: 'A task is a list item with a name, then the module, then msg nested under the module. Quote a msg that contains {{ }}.',
    requires: [['hostname']],
    starter: EMPTY_PLAY,
    solution: task('Display the hostname', "The hostname is {{ ansible_facts['hostname'] }}"),
  },
  {
    id: 't2-kernel',
    title: 'Print the kernel',
    tier: 2,
    prompt: 'Write a task that prints the running kernel release.',
    hint: "Run: ansible servera -m setup | grep -i kernel. You want the release string, not kernel_version.",
    requires: [['kernel']],
    starter: EMPTY_PLAY,
    solution: task('Display the kernel release', "Kernel: {{ ansible_facts['kernel'] }}"),
  },
  {
    id: 't2-memory',
    title: 'Print total memory',
    tier: 2,
    prompt: 'Write a task that prints the total memory in megabytes.',
    hint: "Run: ansible servera -m setup | grep -i mem. The fact you want ends in _mb.",
    requires: [['memtotal_mb']],
    equivalents: [[['memory_mb', 'real', 'total']]],
    starter: EMPTY_PLAY,
    solution: task('Display total memory', "Total memory: {{ ansible_facts['memtotal_mb'] }} MB"),
  },
  {
    id: 't2-selinux',
    title: 'Print the SELinux mode',
    tier: 2,
    prompt: 'Write a task that prints the current SELinux mode (enforcing, permissive, or disabled).',
    hint: "Run: ansible servera -m setup -a 'filter=ansible_selinux'. It is a dictionary; the mode is one level down.",
    requires: [['selinux', 'mode']],
    starter: EMPTY_PLAY,
    solution: task('Display the SELinux mode', "SELinux is {{ ansible_facts['selinux']['mode'] }}"),
  },
  {
    id: 't2-fqdn',
    title: 'Print the FQDN',
    tier: 2,
    prompt: 'Write a task that prints the fully qualified domain name.',
    hint: 'Run: ansible servera -m setup | grep -i fqdn. The fact name is the common four-letter abbreviation.',
    requires: [['fqdn']],
    starter: EMPTY_PLAY,
    solution: task('Display the fully qualified domain name', "FQDN: {{ ansible_facts['fqdn'] }}"),
  },
  {
    id: 't3-os-release',
    title: 'Distribution and version',
    tier: 3,
    prompt: 'Write one task that prints the distribution name and its major version in a single message, for example "CentOS 9".',
    hint: "Two facts, two sets of braces in one msg: 'distribution' and 'distribution_major_version'.",
    requires: [['distribution'], ['distribution_major_version']],
    starter: EMPTY_PLAY,
    solution: task('Display the OS release', "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"),
  },
  {
    id: 't3-network',
    title: 'Interface and address',
    tier: 3,
    prompt: 'Write one task that prints the default-route interface name and its IPv4 address.',
    hint: "Both live under 'default_ipv4': 'interface' and 'address'.",
    requires: [['default_ipv4', 'interface'], ['default_ipv4', 'address']],
    equivalents: [[['default_ipv4', 'alias']], []],
    starter: EMPTY_PLAY,
    solution: task('Display the default interface and address', "{{ ansible_facts['default_ipv4']['interface'] }} has {{ ansible_facts['default_ipv4']['address'] }}"),
  },
  {
    id: 't3-capacity',
    title: 'CPU and memory',
    tier: 3,
    prompt: 'Write one task that prints the number of virtual CPUs and the total memory in megabytes.',
    hint: "Run: ansible servera -m setup | grep -E 'vcpus|memtotal'.",
    requires: [['processor_vcpus'], ['memtotal_mb']],
    equivalents: [[], [['memory_mb', 'real', 'total']]],
    starter: EMPTY_PLAY,
    solution: task('Display CPU and memory', "{{ ansible_facts['processor_vcpus'] }} vCPU, {{ ansible_facts['memtotal_mb'] }} MB"),
  },
  {
    id: 't3-identity',
    title: 'Host identity line',
    tier: 3,
    prompt: 'Write one task that prints three facts in one message: the short hostname, the OS family, and the kernel release.',
    hint: 'Three facts, three sets of braces. The wording between them is yours.',
    requires: [['hostname'], ['os_family'], ['kernel']],
    starter: EMPTY_PLAY,
    solution: task('Display host identity', "{{ ansible_facts['hostname'] }} is a {{ ansible_facts['os_family'] }} host on kernel {{ ansible_facts['kernel'] }}"),
  },
  {
    id: 't3-custom-fact',
    title: 'Custom fact owner',
    tier: 3,
    prompt: "This host has a custom fact, loaded from /etc/ansible/facts.d. Write one task that prints the short hostname and the 'owner' value from that custom fact.",
    hint: "Custom facts appear under 'ansible_local', the one fact that keeps its ansible_ prefix inside ansible_facts. Run: ansible servera -m setup -a 'filter=ansible_local' and follow it down three levels to 'owner'.",
    requires: [['hostname'], ['ansible_local', 'video', 'info', 'owner']],
    starter: EMPTY_PLAY,
    solution: task('Display the custom owner fact', "{{ ansible_facts['hostname'] }} is owned by {{ ansible_facts['ansible_local']['video']['info']['owner'] }}"),
  },
  {
    id: 'capstone',
    title: 'Display Ansible Facts',
    tier: 4,
    prompt: 'Capstone. Write one task named "Display Ansible Facts" that prints five labelled lines as a list under msg: the short hostname, the fully qualified domain name, the distribution with its version, the total memory in megabytes, and the IPv4 address on the 192.168.50.x lab network. The default-route address is the NAT interface, so it is the wrong one here.',
    hint: "msg can be a list: one dash per line, each a quoted string. Run: ansible servera -m setup | grep -A3 all_ipv4 to see both addresses. For the lab address, start from 'all_ipv4_addresses', keep the entries that match the lab subnet with select('match', ...), then take the first.",
    requires: [
      ['hostname'],
      ['fqdn'],
      ['distribution'],
      ['distribution_version'],
      ['memtotal_mb'],
      { value: '192.168.50.11', label: 'the IPv4 address on the 192.168.50.x lab network (start from all_ipv4_addresses)' },
    ],
    equivalents: [[], [], [], [], [['memory_mb', 'real', 'total']]],
    starter: EMPTY_PLAY,
    solution: playbook([
      '- name: Display Ansible Facts',
      '  ansible.builtin.debug:',
      '    msg:',
      `      - "Hostname: {{ ansible_facts['hostname'] }}"`,
      `      - "FQDN: {{ ansible_facts['fqdn'] }}"`,
      `      - "Distribution: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"`,
      `      - "Memory (MB): {{ ansible_facts['memtotal_mb'] }}"`,
      `      - "IPv4: {{ ansible_facts['all_ipv4_addresses'] | select('match', '192.168.50.') | first }}"`,
      '',
    ].join('\n')),
  },
];

// Sixteen fundamentals, then the exam-style scenarios.
export const CHALLENGES = [...FUNDAMENTALS, ...EXAM_CHALLENGES];
