// Generated by tools/sanitize_facts.py from a real `ansible -m setup` capture.
// Do not edit by hand; re-run the sanitizer.
export const HOST = "servera";
export const FACTS = {
  "all_ipv4_addresses": [
    "10.0.2.15",
    "192.168.50.11"
  ],
  "all_ipv6_addresses": [
    "fd17:625c:f037:2:200:5eff:fe00:5301",
    "fe80::200:5eff:fe00:5301",
    "fe80::200:5eff:fe00:53ff"
  ],
  "ansible_local": {
    "video": {
      "info": {
        "owner": "student"
      }
    }
  },
  "apparmor": {
    "status": "disabled"
  },
  "architecture": "aarch64",
  "bios_date": "NA",
  "bios_vendor": "NA",
  "bios_version": "NA",
  "board_asset_tag": "NA",
  "board_name": "NA",
  "board_serial": "NA",
  "board_vendor": "NA",
  "board_version": "NA",
  "chassis_asset_tag": "NA",
  "chassis_serial": "NA",
  "chassis_vendor": "NA",
  "chassis_version": "NA",
  "cmdline": {
    "BOOT_IMAGE": "(hd0,gpt2)/vmlinuz-5.14.0-754.el9.aarch64",
    "crashkernel": "1G-4G:256M,4G-64G:320M,64G-:576M",
    "rd.lvm.lv": "cs/swap",
    "ro": true,
    "root": "/dev/mapper/cs-root"
  },
  "date_time": {
    "date": "2026-10-09",
    "day": "09",
    "epoch": "1791557121",
    "epoch_int": "1791557121",
    "hour": "10",
    "iso8601": "2026-10-09T14:45:21Z",
    "iso8601_basic": "20261009T104521933082",
    "iso8601_basic_short": "20261009T104521",
    "iso8601_micro": "2026-10-09T14:45:21.933082Z",
    "minute": "45",
    "month": "10",
    "second": "21",
    "time": "10:45:21",
    "tz": "EDT",
    "tz_dst": "EDT",
    "tz_offset": "-0400",
    "weekday": "Friday",
    "weekday_number": "5",
    "weeknumber": "40",
    "year": "2026"
  },
  "default_ipv4": {
    "address": "10.0.2.15",
    "alias": "enp0s8",
    "broadcast": "10.0.2.255",
    "gateway": "10.0.2.2",
    "interface": "enp0s8",
    "macaddress": "00:00:5e:00:53:01",
    "mtu": 1500,
    "netmask": "255.255.255.0",
    "network": "10.0.2.0",
    "prefix": "24",
    "type": "ether"
  },
  "default_ipv6": {
    "address": "fd17:625c:f037:2:200:5eff:fe00:5301",
    "gateway": "fe80::2",
    "interface": "enp0s8",
    "macaddress": "00:00:5e:00:53:01",
    "mtu": 1500,
    "prefix": "64",
    "scope": "global",
    "type": "ether"
  },
  "device_links": {
    "ids": {
      "dm-0": [
        "dm-name-cs-root",
        "dm-uuid-LVM-PLACEHOLDER01"
      ],
      "dm-1": [
        "dm-name-cs-swap",
        "dm-uuid-LVM-PLACEHOLDER02"
      ],
      "sda3": [
        "lvm-pv-uuid-PLACEHOLDER01"
      ]
    },
    "labels": {},
    "masters": {
      "sda3": [
        "dm-0",
        "dm-1"
      ]
    },
    "uuids": {
      "dm-0": [
        "00000000-0000-4000-8000-000000000002"
      ],
      "dm-1": [
        "00000000-0000-4000-8000-000000000003"
      ],
      "sda1": [
        "0000-0001"
      ],
      "sda2": [
        "00000000-0000-4000-8000-000000000004"
      ]
    }
  },
  "devices": {
    "dm-0": {
      "holders": [],
      "host": "",
      "links": {
        "ids": [
          "dm-name-cs-root",
          "dm-uuid-LVM-PLACEHOLDER01"
        ],
        "labels": [],
        "masters": [],
        "uuids": [
          "00000000-0000-4000-8000-000000000002"
        ]
      },
      "model": null,
      "partitions": {},
      "removable": "0",
      "rotational": "1",
      "sas_address": null,
      "sas_device_handle": null,
      "scheduler_mode": "",
      "sectors": "34414592",
      "sectorsize": "512",
      "size": "16.41 GB",
      "support_discard": "0",
      "vendor": null,
      "virtual": 1
    },
    "dm-1": {
      "holders": [],
      "host": "",
      "links": {
        "ids": [
          "dm-name-cs-swap",
          "dm-uuid-LVM-PLACEHOLDER02"
        ],
        "labels": [],
        "masters": [],
        "uuids": [
          "00000000-0000-4000-8000-000000000003"
        ]
      },
      "model": null,
      "partitions": {},
      "removable": "0",
      "rotational": "1",
      "sas_address": null,
      "sas_device_handle": null,
      "scheduler_mode": "",
      "sectors": "4194304",
      "sectorsize": "512",
      "size": "2.00 GB",
      "support_discard": "0",
      "vendor": null,
      "virtual": 1
    },
    "sda": {
      "holders": [],
      "host": "",
      "links": {
        "ids": [],
        "labels": [],
        "masters": [],
        "uuids": []
      },
      "model": "HARDDISK",
      "partitions": {
        "sda1": {
          "holders": [],
          "links": {
            "ids": [],
            "labels": [],
            "masters": [],
            "uuids": [
              "0000-0001"
            ]
          },
          "sectors": "1228800",
          "sectorsize": 512,
          "size": "600.00 MB",
          "start": "2048",
          "uuid": "0000-0001"
        },
        "sda2": {
          "holders": [],
          "links": {
            "ids": [],
            "labels": [],
            "masters": [],
            "uuids": [
              "00000000-0000-4000-8000-000000000004"
            ]
          },
          "sectors": "2097152",
          "sectorsize": 512,
          "size": "1.00 GB",
          "start": "1230848",
          "uuid": "00000000-0000-4000-8000-000000000004"
        },
        "sda3": {
          "holders": [
            "cs-swap",
            "cs-root"
          ],
          "links": {
            "ids": [
              "lvm-pv-uuid-PLACEHOLDER01"
            ],
            "labels": [],
            "masters": [
              "dm-0",
              "dm-1"
            ],
            "uuids": []
          },
          "sectors": "38612992",
          "sectorsize": 512,
          "size": "18.41 GB",
          "start": "3328000",
          "uuid": null
        }
      },
      "removable": "0",
      "rotational": "1",
      "sas_address": null,
      "sas_device_handle": null,
      "scheduler_mode": "mq-deadline",
      "sectors": "41943040",
      "sectorsize": "512",
      "size": "20.00 GB",
      "support_discard": "0",
      "vendor": "VBOX",
      "virtual": 1
    },
    "sr0": {
      "holders": [],
      "host": "",
      "links": {
        "ids": [],
        "labels": [],
        "masters": [],
        "uuids": []
      },
      "model": "CD-ROM",
      "partitions": {},
      "removable": "1",
      "rotational": "0",
      "sas_address": null,
      "sas_device_handle": null,
      "scheduler_mode": "mq-deadline",
      "sectors": "2097151",
      "sectorsize": "512",
      "size": "1024.00 MB",
      "support_discard": "0",
      "vendor": "VBOX",
      "virtual": 1
    }
  },
  "discovered_interpreter_python": "/usr/bin/python3",
  "distribution": "CentOS",
  "distribution_file_parsed": true,
  "distribution_file_path": "/etc/centos-release",
  "distribution_file_variety": "CentOS",
  "distribution_major_version": "9",
  "distribution_release": "Stream",
  "distribution_version": "9",
  "dns": {
    "nameservers": [
      "192.0.2.53",
      "192.168.3.1",
      "fd17:625c:f037:2::3"
    ],
    "search": [
      "ytt.lab"
    ]
  },
  "domain": "ytt.lab",
  "effective_group_id": 1000,
  "effective_user_id": 1000,
  "enp0s8": {
    "active": true,
    "device": "enp0s8",
    "features": {
      "esp_hw_offload": "off [fixed]",
      "esp_tx_csum_hw_offload": "off [fixed]",
      "generic_receive_offload": "on",
      "generic_segmentation_offload": "on",
      "highdma": "off [fixed]",
      "hsr_dup_offload": "off [fixed]",
      "hsr_fwd_offload": "off [fixed]",
      "hsr_tag_ins_offload": "off [fixed]",
      "hsr_tag_rm_offload": "off [fixed]",
      "hw_tc_offload": "off [fixed]",
      "l2_fwd_offload": "off [fixed]",
      "large_receive_offload": "off [fixed]",
      "loopback": "off [fixed]",
      "macsec_hw_offload": "off [fixed]",
      "ntuple_filters": "off [fixed]",
      "receive_hashing": "off [fixed]",
      "rx_all": "off",
      "rx_checksumming": "off",
      "rx_fcs": "off",
      "rx_gro_hw": "off [fixed]",
      "rx_gro_list": "off",
      "rx_udp_gro_forwarding": "off",
      "rx_udp_tunnel_port_offload": "off [fixed]",
      "rx_vlan_filter": "on [fixed]",
      "rx_vlan_offload": "on",
      "rx_vlan_stag_filter": "off [fixed]",
      "rx_vlan_stag_hw_parse": "off [fixed]",
      "scatter_gather": "on",
      "tcp_segmentation_offload": "on",
      "tls_hw_record": "off [fixed]",
      "tls_hw_rx_offload": "off [fixed]",
      "tls_hw_tx_offload": "off [fixed]",
      "tx_checksum_fcoe_crc": "off [fixed]",
      "tx_checksum_ip_generic": "on",
      "tx_checksum_ipv4": "off [fixed]",
      "tx_checksum_ipv6": "off [fixed]",
      "tx_checksum_sctp": "off [fixed]",
      "tx_checksumming": "on",
      "tx_esp_segmentation": "off [fixed]",
      "tx_fcoe_segmentation": "off [fixed]",
      "tx_gre_csum_segmentation": "off [fixed]",
      "tx_gre_segmentation": "off [fixed]",
      "tx_gso_list": "off [fixed]",
      "tx_gso_partial": "off [fixed]",
      "tx_gso_robust": "off [fixed]",
      "tx_ipxip4_segmentation": "off [fixed]",
      "tx_ipxip6_segmentation": "off [fixed]",
      "tx_nocache_copy": "off",
      "tx_scatter_gather": "on",
      "tx_scatter_gather_fraglist": "off [fixed]",
      "tx_sctp_segmentation": "off [fixed]",
      "tx_tcp6_segmentation": "off [fixed]",
      "tx_tcp_ecn_segmentation": "off [fixed]",
      "tx_tcp_mangleid_segmentation": "off",
      "tx_tcp_segmentation": "on",
      "tx_tunnel_remcsum_segmentation": "off [fixed]",
      "tx_udp_segmentation": "off [fixed]",
      "tx_udp_tnl_csum_segmentation": "off [fixed]",
      "tx_udp_tnl_segmentation": "off [fixed]",
      "tx_vlan_offload": "on [fixed]",
      "tx_vlan_stag_hw_insert": "off [fixed]",
      "vlan_challenged": "off [fixed]"
    },
    "hw_timestamp_filters": [],
    "ipv4": {
      "address": "10.0.2.15",
      "broadcast": "10.0.2.255",
      "netmask": "255.255.255.0",
      "network": "10.0.2.0",
      "prefix": "24"
    },
    "ipv6": [
      {
        "address": "fd17:625c:f037:2:200:5eff:fe00:5301",
        "prefix": "64",
        "scope": "global"
      },
      {
        "address": "fe80::200:5eff:fe00:5301",
        "prefix": "64",
        "scope": "link"
      }
    ],
    "macaddress": "00:00:5e:00:53:01",
    "module": "e1000",
    "mtu": 1500,
    "pciid": "0000:00:08.0",
    "promisc": false,
    "speed": 1000,
    "timestamping": [],
    "type": "ether"
  },
  "enp0s9": {
    "active": true,
    "device": "enp0s9",
    "features": {
      "esp_hw_offload": "off [fixed]",
      "esp_tx_csum_hw_offload": "off [fixed]",
      "generic_receive_offload": "on",
      "generic_segmentation_offload": "on",
      "highdma": "off [fixed]",
      "hsr_dup_offload": "off [fixed]",
      "hsr_fwd_offload": "off [fixed]",
      "hsr_tag_ins_offload": "off [fixed]",
      "hsr_tag_rm_offload": "off [fixed]",
      "hw_tc_offload": "off [fixed]",
      "l2_fwd_offload": "off [fixed]",
      "large_receive_offload": "off [fixed]",
      "loopback": "off [fixed]",
      "macsec_hw_offload": "off [fixed]",
      "ntuple_filters": "off [fixed]",
      "receive_hashing": "off [fixed]",
      "rx_all": "off",
      "rx_checksumming": "off",
      "rx_fcs": "off",
      "rx_gro_hw": "off [fixed]",
      "rx_gro_list": "off",
      "rx_udp_gro_forwarding": "off",
      "rx_udp_tunnel_port_offload": "off [fixed]",
      "rx_vlan_filter": "on [fixed]",
      "rx_vlan_offload": "on",
      "rx_vlan_stag_filter": "off [fixed]",
      "rx_vlan_stag_hw_parse": "off [fixed]",
      "scatter_gather": "on",
      "tcp_segmentation_offload": "on",
      "tls_hw_record": "off [fixed]",
      "tls_hw_rx_offload": "off [fixed]",
      "tls_hw_tx_offload": "off [fixed]",
      "tx_checksum_fcoe_crc": "off [fixed]",
      "tx_checksum_ip_generic": "on",
      "tx_checksum_ipv4": "off [fixed]",
      "tx_checksum_ipv6": "off [fixed]",
      "tx_checksum_sctp": "off [fixed]",
      "tx_checksumming": "on",
      "tx_esp_segmentation": "off [fixed]",
      "tx_fcoe_segmentation": "off [fixed]",
      "tx_gre_csum_segmentation": "off [fixed]",
      "tx_gre_segmentation": "off [fixed]",
      "tx_gso_list": "off [fixed]",
      "tx_gso_partial": "off [fixed]",
      "tx_gso_robust": "off [fixed]",
      "tx_ipxip4_segmentation": "off [fixed]",
      "tx_ipxip6_segmentation": "off [fixed]",
      "tx_nocache_copy": "off",
      "tx_scatter_gather": "on",
      "tx_scatter_gather_fraglist": "off [fixed]",
      "tx_sctp_segmentation": "off [fixed]",
      "tx_tcp6_segmentation": "off [fixed]",
      "tx_tcp_ecn_segmentation": "off [fixed]",
      "tx_tcp_mangleid_segmentation": "off",
      "tx_tcp_segmentation": "on",
      "tx_tunnel_remcsum_segmentation": "off [fixed]",
      "tx_udp_segmentation": "off [fixed]",
      "tx_udp_tnl_csum_segmentation": "off [fixed]",
      "tx_udp_tnl_segmentation": "off [fixed]",
      "tx_vlan_offload": "on [fixed]",
      "tx_vlan_stag_hw_insert": "off [fixed]",
      "vlan_challenged": "off [fixed]"
    },
    "hw_timestamp_filters": [],
    "ipv4": {
      "address": "192.168.50.11",
      "broadcast": "192.168.50.255",
      "netmask": "255.255.255.0",
      "network": "192.168.50.0",
      "prefix": "24"
    },
    "ipv6": [
      {
        "address": "fe80::200:5eff:fe00:53ff",
        "prefix": "64",
        "scope": "link"
      }
    ],
    "macaddress": "00:00:5e:00:53:02",
    "module": "e1000",
    "mtu": 1500,
    "pciid": "0000:00:09.0",
    "promisc": false,
    "speed": 1000,
    "timestamping": [],
    "type": "ether"
  },
  "env": {
    "BASH_FUNC_which%%": "() {  ( alias;\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@\n}",
    "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
    "DEBUGINFOD_IMA_CERT_PATH": "/etc/keys/ima:",
    "DEBUGINFOD_URLS": "https://debuginfod.centos.org/ ",
    "HOME": "/home/student",
    "LANG": "en_US.UTF-8",
    "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
    "LOGNAME": "student",
    "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:",
    "MOTD_SHOWN": "pam",
    "PATH": "/home/student/.local/bin:/home/student/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin",
    "PWD": "/home/student",
    "SELINUX_LEVEL_REQUESTED": "",
    "SELINUX_ROLE_REQUESTED": "",
    "SELINUX_USE_CURRENT_RANGE": "",
    "SHELL": "/bin/bash",
    "SHLVL": "1",
    "SSH_CLIENT": "192.168.50.10 41824 22",
    "SSH_CONNECTION": "192.168.50.10 41824 192.168.50.11 22",
    "SSH_TTY": "/dev/pts/0",
    "TERM": "xterm-256color",
    "USER": "student",
    "XDG_RUNTIME_DIR": "/run/user/1000",
    "XDG_SESSION_CLASS": "user",
    "XDG_SESSION_ID": "97",
    "XDG_SESSION_TYPE": "tty",
    "_": "/usr/bin/python3",
    "which_declare": "declare -f"
  },
  "fibre_channel_wwn": [],
  "fips": false,
  "form_factor": "NA",
  "fqdn": "servera.ytt.lab",
  "gather_subset": [
    "all"
  ],
  "hostname": "servera",
  "hostnqn": "nqn.2014-08.org.nvmexpress:uuid:00000000-0000-4000-8000-000000000001",
  "interfaces": [
    "enp0s9",
    "enp0s8",
    "lo"
  ],
  "is_chroot": false,
  "iscsi_iqn": "",
  "kernel": "5.14.0-754.el9.aarch64",
  "kernel_version": "#1 SMP PREEMPT_DYNAMIC Tue Sep 29 10:44:40 UTC 2026",
  "lo": {
    "active": true,
    "device": "lo",
    "features": {
      "esp_hw_offload": "off [fixed]",
      "esp_tx_csum_hw_offload": "off [fixed]",
      "generic_receive_offload": "on",
      "generic_segmentation_offload": "on",
      "highdma": "on [fixed]",
      "hsr_dup_offload": "off [fixed]",
      "hsr_fwd_offload": "off [fixed]",
      "hsr_tag_ins_offload": "off [fixed]",
      "hsr_tag_rm_offload": "off [fixed]",
      "hw_tc_offload": "off [fixed]",
      "l2_fwd_offload": "off [fixed]",
      "large_receive_offload": "off [fixed]",
      "loopback": "on [fixed]",
      "macsec_hw_offload": "off [fixed]",
      "ntuple_filters": "off [fixed]",
      "receive_hashing": "off [fixed]",
      "rx_all": "off [fixed]",
      "rx_checksumming": "on [fixed]",
      "rx_fcs": "off [fixed]",
      "rx_gro_hw": "off [fixed]",
      "rx_gro_list": "off",
      "rx_udp_gro_forwarding": "off",
      "rx_udp_tunnel_port_offload": "off [fixed]",
      "rx_vlan_filter": "off [fixed]",
      "rx_vlan_offload": "off [fixed]",
      "rx_vlan_stag_filter": "off [fixed]",
      "rx_vlan_stag_hw_parse": "off [fixed]",
      "scatter_gather": "on",
      "tcp_segmentation_offload": "on",
      "tls_hw_record": "off [fixed]",
      "tls_hw_rx_offload": "off [fixed]",
      "tls_hw_tx_offload": "off [fixed]",
      "tx_checksum_fcoe_crc": "off [fixed]",
      "tx_checksum_ip_generic": "on [fixed]",
      "tx_checksum_ipv4": "off [fixed]",
      "tx_checksum_ipv6": "off [fixed]",
      "tx_checksum_sctp": "on [fixed]",
      "tx_checksumming": "on",
      "tx_esp_segmentation": "off [fixed]",
      "tx_fcoe_segmentation": "off [fixed]",
      "tx_gre_csum_segmentation": "off [fixed]",
      "tx_gre_segmentation": "off [fixed]",
      "tx_gso_list": "on",
      "tx_gso_partial": "off [fixed]",
      "tx_gso_robust": "off [fixed]",
      "tx_ipxip4_segmentation": "off [fixed]",
      "tx_ipxip6_segmentation": "off [fixed]",
      "tx_nocache_copy": "off [fixed]",
      "tx_scatter_gather": "on [fixed]",
      "tx_scatter_gather_fraglist": "on [fixed]",
      "tx_sctp_segmentation": "on",
      "tx_tcp6_segmentation": "on",
      "tx_tcp_ecn_segmentation": "on",
      "tx_tcp_mangleid_segmentation": "on",
      "tx_tcp_segmentation": "on",
      "tx_tunnel_remcsum_segmentation": "off [fixed]",
      "tx_udp_segmentation": "on",
      "tx_udp_tnl_csum_segmentation": "off [fixed]",
      "tx_udp_tnl_segmentation": "off [fixed]",
      "tx_vlan_offload": "off [fixed]",
      "tx_vlan_stag_hw_insert": "off [fixed]",
      "vlan_challenged": "on [fixed]"
    },
    "hw_timestamp_filters": [],
    "ipv4": {
      "address": "127.0.0.1",
      "broadcast": "",
      "netmask": "255.0.0.0",
      "network": "127.0.0.0",
      "prefix": "8"
    },
    "ipv6": [
      {
        "address": "::1",
        "prefix": "128",
        "scope": "host"
      }
    ],
    "mtu": 65536,
    "promisc": false,
    "timestamping": [],
    "type": "loopback"
  },
  "loadavg": {
    "15m": 0.0,
    "1m": 0.0,
    "5m": 0.0
  },
  "lsb": {},
  "lvm": "N/A",
  "machine": "aarch64",
  "machine_id": "0123456789abcdef0123456789abcdef",
  "memfree_mb": 109,
  "memory_mb": {
    "nocache": {
      "free": 381,
      "used": 186
    },
    "real": {
      "free": 109,
      "total": 567,
      "used": 458
    },
    "swap": {
      "cached": 0,
      "free": 2047,
      "total": 2047,
      "used": 0
    }
  },
  "memtotal_mb": 567,
  "module_setup": true,
  "mounts": [
    {
      "block_available": 3737131,
      "block_size": 4096,
      "block_total": 4285440,
      "block_used": 548309,
      "device": "/dev/mapper/cs-root",
      "fstype": "xfs",
      "inode_available": 8561498,
      "inode_total": 8603648,
      "inode_used": 42150,
      "mount": "/",
      "options": "rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota",
      "size_available": 15307288576,
      "size_total": 17553162240,
      "uuid": "00000000-0000-4000-8000-000000000002"
    },
    {
      "block_available": 146847,
      "block_size": 4096,
      "block_total": 245760,
      "block_used": 98913,
      "device": "/dev/sda2",
      "fstype": "xfs",
      "inode_available": 523834,
      "inode_total": 524288,
      "inode_used": 454,
      "mount": "/boot",
      "options": "rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota",
      "size_available": 601485312,
      "size_total": 1006632960,
      "uuid": "00000000-0000-4000-8000-000000000004"
    },
    {
      "block_available": 151407,
      "block_size": 4096,
      "block_total": 153296,
      "block_used": 1889,
      "device": "/dev/sda1",
      "fstype": "vfat",
      "inode_available": 0,
      "inode_total": 0,
      "inode_used": 0,
      "mount": "/boot/efi",
      "options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro",
      "size_available": 620163072,
      "size_total": 627900416,
      "uuid": "0000-0001"
    }
  ],
  "nodename": "servera.ytt.lab",
  "os_family": "RedHat",
  "pkg_mgr": "dnf",
  "proc_cmdline": {
    "BOOT_IMAGE": "(hd0,gpt2)/vmlinuz-5.14.0-754.el9.aarch64",
    "crashkernel": "1G-4G:256M,4G-64G:320M,64G-:576M",
    "rd.lvm.lv": [
      "cs/root",
      "cs/swap"
    ],
    "ro": true,
    "root": "/dev/mapper/cs-root"
  },
  "processor": [
    "0"
  ],
  "processor_cores": 1,
  "processor_count": 1,
  "processor_nproc": 1,
  "processor_threads_per_core": 1,
  "processor_vcpus": 1,
  "product_name": "NA",
  "product_serial": "NA",
  "product_uuid": "NA",
  "product_version": "NA",
  "python": {
    "executable": "/usr/bin/python3",
    "has_sslcontext": true,
    "type": "cpython",
    "version": {
      "major": 3,
      "micro": 25,
      "minor": 9,
      "releaselevel": "final",
      "serial": 0
    },
    "version_info": [
      3,
      9,
      25,
      "final",
      0
    ]
  },
  "python_version": "3.9.25",
  "real_group_id": 1000,
  "real_user_id": 1000,
  "selinux": {
    "config_mode": "enforcing",
    "mode": "enforcing",
    "policyvers": 33,
    "status": "enabled",
    "type": "targeted"
  },
  "selinux_python_present": true,
  "service_mgr": "systemd",
  "ssh_host_key_ecdsa_public": "AAAAECDSAPLACEHOLDERKEYNOTREAL",
  "ssh_host_key_ecdsa_public_keytype": "ecdsa-sha2-nistp256",
  "ssh_host_key_ed25519_public": "AAAAED25519PLACEHOLDERKEYNOTREAL",
  "ssh_host_key_ed25519_public_keytype": "ssh-ed25519",
  "ssh_host_key_rsa_public": "AAAARSAPLACEHOLDERKEYNOTREAL",
  "ssh_host_key_rsa_public_keytype": "ssh-rsa",
  "swapfree_mb": 2047,
  "swaptotal_mb": 2047,
  "system": "Linux",
  "system_capabilities": [
    ""
  ],
  "system_capabilities_enforced": "True",
  "system_vendor": "NA",
  "uptime_seconds": 74175,
  "user_dir": "/home/student",
  "user_gecos": "",
  "user_gid": 1000,
  "user_id": "student",
  "user_shell": "/bin/bash",
  "user_uid": 1000,
  "userspace_bits": "64",
  "virtualization_role": "NA",
  "virtualization_tech_guest": [],
  "virtualization_tech_host": [],
  "virtualization_type": "NA"
};
